import accent from "../images/accent.png";
import elantra from "../images/elantra.png";
import sonata from "../images/sonata.png";
import mazda6 from "../images/mazda6.png";
import camry from "../images/camry.png";
import cx5 from "../images/cx5.png";
import siena from "../images/siena.png";

let state = {
  cars: [
    {
      name: "Hyundai Accent",
      src: accent,
      type: "Седан",
      fuel: "9",
      fuelType: "A92/A95",
      transmission: "Ручная",
      seats: "5",
      condicioner: "Есть",
      bluetooth: "Нет",
      seatsWarm: "Нет",
      camera: "Нет",
    },
    {
      name: "Hyundai Elantra",
      src: elantra,
      fuel: "10",
      fuelType: "A92/A95",
      transmission: "Автомат",
      seats: "5",
      condicioner: "Есть",
      bluetooth: "Есть",
      seatsWarm: "Нет",
      camera: "Нет",
    },
    {
      name: "Hyundai Sonata",
      src: sonata,
      type: "Седан",
      fuel: "13.5",
      fuelType: "A95",
      transmission: "Автомат",
      seats: "5",
      condicioner: "Есть",
      bluetooth: "Есть",
      seatsWarm: "Нет",
      camera: "Есть",
    },
    {
      name: "Mazda 6",
      src: mazda6,
      type: "Седан",
      fuel: "10",
      fuelType: "A95",
      transmission: "Автомат",
      seats: "5",
      condicioner: "Климат-контроль",
      bluetooth: "Есть",
      seatsWarm: "Есть",
      camera: "Есть",
    },
    {
      name: "Toyota Camry",
      src: camry,
      type: "Седан",
      fuel: "15",
      fuelType: "A95",
      transmission: "Автомат",
      seats: "5",
      condicioner: "Климат-контроль",
      bluetooth: "Есть",
      seatsWarm: "Есть",
      camera: "Есть",
    },
    {
      name: "Mazda CX5",
      src: cx5,
      type: "Внедорожник",
      fuel: "14.5",
      fuelType: "A95",
      transmission: "Автомат",
      seats: "5",
      condicioner: "Климат-контроль",
      bluetooth: "Есть",
      seatsWarm: "Есть",
      camera: "Есть",
    },
    {
      name: "Toyota Sienna",
      src: siena,
      type: "Минивен",
      fuel: "16.5",
      fuelType: "A95",
      transmission: "Автомат",
      seats: "8",
      condicioner: "Климат-контроль",
      bluetooth: "Есть",
      seatsWarm: "Есть",
      camera: "Есть",
    },
  ],
  price: [
    {
      name: "Hyundai Accent",
      src: accent,
      days1_3: "700",
      days4_7: "650",
      days8_14: "600",
      long: "договорная",
      deposit: "5000",
    },
    {
      name: "Hyundai Elantra",
      src: elantra,
      days1_3: "900",
      days4_7: "850",
      days8_14: "800",
      long: "договорная",
      deposit: "7000",
    },
    {
      name: "Hyundai Sonata",
      src: sonata,
      days1_3: "1100",
      days4_7: "1050",
      days8_14: "1000",
      long: "договорная",
      deposit: "8000",
    },
    {
      name: "Mazda 6",
      src: mazda6,
      days1_3: "1100",
      days4_7: "1050",
      days8_14: "1000",
      long: "договорная",
      deposit: "8000",
    },
    {
      name: "Toyota Camry",
      src: camry,
      days1_3: "1300",
      days4_7: "1200",
      days8_14: "1100",
      long: "договорная",
      deposit: "10000",
    },
    {
      name: "Mazda CX5",
      src: cx5,
      days1_3: "1300",
      days4_7: "1200",
      days8_14: "1100",
      long: "договорная",
      deposit: "10000",
    },
    {
      name: "Toyota Sienna",
      src: siena,
      days1_3: "1500",
      days4_7: "1450",
      days8_14: "1400",
      long: "договорная",
      deposit: "12000",
    },
  ],
};

export default state;
